#!/bin/bash

#This script takes the function of wget 
#As parameters set the link you would like to download the file from, and an optional name for it otherwise it will take the original name saved in the link
#Example: user$ wget myLink.com/myDocument.pdf [Dcoument.pdf]
#if Document.pdf is added it will be saved as such otherwise as myDocument.pdf as in the link

if [[ $# -ne 1 && $# -ne 2 ]]
then
	if [ $# -eq 0 ]
		echo "//No arguments inserted Ex: wget myLink.com/myDocument.pdf"
		exit -1
	else
		echo "//Too many arguments inserted Ex: wget myLink.com/myDocument.pdf Dcoument.pdf"
		exit -1
	fi
fi

if [ $# -eq 1 ]
then
	name=$(basename $1)

else
	name=$2
fi


curl $1 > $name

exit 0
